% BIS
items_str = {'1. I plan tasks carefully.', ...
        '2. I do things without thinking.', ...
        '3. I make-up my mind quickly.', ...
        '4. I am happy-go-lucky.', ...
        '5. I don''t "pay attention".', ...
        '6. I have "racing" thoughts.', ...
        '7. I plan trips well ahead of time.', ...
        '8. I am self controlled.', ...
        '9. I concentrate easily.', ...
        '10. I save regularly.', ...
        '11. I "squirm" at plays or lectures.', ...
        '12. I am a careful thinker.', ...
        '13. I plan for job security.', ...
        '14. I say things without thinking.', ...
        '15. I like to think about complex problems.', ...
        '16. I change jobs.', ...
        '17. I act "on impulse".', ...
        '18. I get easily bored when solving thought problems.', ...
        '19. I act on the spur of the moment.', ...
        '20. I am a steady thinker.', ...
        '21. I change residences.', ...
        '22. I buy things on impulse.', ...
        '23. I can only think about one thing at a time.', ...
        '24. I change hobbies.', ...
        '25. I spend or charge more than I earn.', ...
        '26. I often have extraneous thoughts when thinking.', ...
        '27. I am more interested in the present than the future.', ...
        '28. I am restless at the theater or lectures.', ...
        '29. I like puzzles.', ...
        '30. I am future oriented.' };
      
save('items_string/items_BIS.mat', 'items_str')


% ASRS
items_str = {'1. How often do you have trouble wrapping up the final details of a project, once the challenging parts have been done?', ...
        '2. How often do you have difficulty getting things in order when you have to do a task that requires organization?', ...
        '3. How often do you have problems remembering appointments or obligations?', ...
        '4. When you have a task that requires a lot of thought, how often do you avoid or delay getting started?', ...
        '5. How often do you fidget or squirm with your hands or feet when you have to sit down for a long time?', ...
        '6. How often do you feel overly active and compelled to do things, like you were driven by a motor?', ...
        '7. How often do you make careless mistakes when you have to work on a boring or difficult project?', ...
        '8. How often do you have difficulty keeping your attention when you are doing boring or repetitive work?', ...
        '9. How often do you have difficulty concentrating on what people say to you, even when they are speaking to you directly?', ...
        '10. How often do you misplace or have difficulty finding things at home or at work?', ...
        '11. How often are you distracted by activity or noise around you?', ...
        '12. How often do you leave your seat in meetings or other situations in which you are expected to remain seated?', ...
        '13. How often do you feel restless or fidgety?', ...
        '14. How often do you have difficulty unwinding and relaxing when you have time to yourself?', ...
        '15. How often do you find yourself talking too much when you are in social situations?', ...
        '16. When you''re in a conversation, how often do you find yourself finishing the sentences of the people you are talking to, before they can finish them themselves?', ...
        '17. How often do you have difficulty waiting your turn in situations when turn taking is required?', ...
        '18. How often do you interrupt others when they are busy?'};

save('items_string/items_ASRS.mat', 'items_str')


% OCIR
items_str = {'1. I have saved up so many things that they get in the way.', ...
        '2. I check things more often than necessary.', ...
        '3. I get upset if objects are not arranged properly.', ...
        '4. I feel compelled to count while I am doing things.', ...
        '5. I find it difficult to touch an object when I know it has been touched by strangers or certain people.', ...
        '6. I find it difficult to control my own thoughts.', ...
        '7. I collect things I don''t need.', ...
        '8. I repeatedly check doors, windows, drawers, etc.', ...
        '9. I get upset if others change the way I have arranged things.', ...
        '10. I feel I have to repeat certain numbers.', ...
        '11. I sometimes have to wash or clean myself simply because I feel contaminated.', ...
        '12. I am upset by unpleasant thoughts that come into my mind against my will.', ...
        '13. I avoid throwing things away because I am afraid I might need them later.', ...
        '14. I repeatedly check gas and water taps and light switches after turning them off.', ...
        '15. I need things to be arranged in a particular way.', ...
        '16. I feel that there are good and bad numbers.', ...
        '17. I wash my hands more often and longer than necessary.', ...
        '18. I frequently get nasty thoughts and have difficulty in getting rid of them.'};
      
save('items_string/items_OCIR.mat', 'items_str')


% SDS
items_str = {'1. I feel down-hearted and blue.', ...
         '2. Morning is when I feel the best.', ...
         '3. I have crying spells or feel like it.', ...
         '4. I have trouble sleeping at night.', ...
         '5. I eat as much as I used to.', ...
         '6. I still enjoy sex.', ...
         '7. I notice that I am losing weight.', ...
         '8. I have trouble with constipation.', ...
         '9. My heart beats faster than usual.', ...
         '10. I get tired for no reason.', ...
         '11. My mind is as clear as it used to be.', ...
         '12. I find it easy to do the things I used to.', ...
         '13. I am restless and can''t keep still.', ...
         '14. I feel hopeful about the future.', ...
         '15. I am more irritable than usual.', ...
         '16. I find it easy to make decisions.', ...
         '17. I feel that I am useful and needed.', ...
         '18. My life is pretty full.', ...
         '19. I feel that others would be better off if I were dead.', ...
         '20. I still enjoy the things I used to do.'};
       
save('items_string/items_SDS.mat', 'items_str')


% STAI 
items_str = {'1. I feel pleasant', ...
        '2. I feel nervous and restless', ...
        '3. I feel satisfied with myself', ...
        '4. I wish I could be as happy as others seem to be', ...
        '5. I feel like a failure', ...
        '6. I feel rested', ...
        '7. I am calm, cool, and collected', ...
        '8. I feel that difficulties are piling up so that I cannot overcome them', ...
        '9. I worry too much over something that really doesn''t matter', ...
        '10. I am happy', ...
        '11. I have disturbing thoughts', ...
        '12. I lack self confidence', ...
        '13. I feel secure', ...
        '14. I make decision easily', ...
        '15. I feel inadequate', ...
        '16. I am content', ...
        '17. Some unimportant thoughts runs through my mind and bothers me', ...
        '18. I take disappointments so keenly that I can''t put them out of my mind', ...
        '19. I am a steady person', ...
        '20. I get in a state of tension or turmoil as I think over my recent concerns and interests'};

 save('items_string/items_STAI.mat', 'items_str')
 
 
% IUS
items_str = {'1. Uncertainty stops me from having a firm opinion.', ...
        '2. Being uncertain means that a person is disorganized.', ...
        '3. Uncertainty makes life intolerable.', ...
        '4. it''s unfair not having any guarantees in life.', ...
        '5. My mind can''t be relaxed if I don''t know what will happen tomorrow.', ...
        '6. Uncertainty makes me uneasy, anxious, or stressed.', ...
        '7. Unforeseen events upset me greatly.', ...
        '8. It frustrates me not having all the information I need.', ...
        '9. Uncertainty keeps me from living a full life.', ...
        '10. One should always look ahead so as to avoid surprises.', ...
        '11. A small unforeseen event can spoil everything, even with the best of planning.', ...
        '12. When it''s time to act, uncertainty paralyses me.', ...
        '13. Being uncertain means that I am not first rate.', ...
        '14. When I am uncertain, I can''t go forward.', ...
        '15. When I am uncertain I can''t function very well.', ...
        '16. Unlike me, others always seem to know where they are going with their lives.', ...
        '17. Uncertainty makes me vulnerable, unhappy, or sad.', ...
        '18. I always want to know what the future has in store for me.', ...
        '19. I can''t stand being taken by surprise.', ...
        '20. The smallest doubt can stop me from acting.', ...
        '21. I should be able to organize everything in advance.', ...
        '22. Being uncertain means that I lack confidence.', ...
        '23. I think it''s unfair that other people seem sure about their future.', ...
        '24. Uncertainty keeps me from sleeping soundly.', ...
        '25. I must get away from all uncertain situations.', ...
        '26. The ambiguities in life stress me.', ...
        '27. I can''t stand being undecided about my future.'};
      
 save('items_string/items_IUS.mat', 'items_str')
  
 
% CFS        
items_str = {'1. I can communicate an idea in many different ways.', ...
        '2. I avoid new and unusual situations.', ...
        '3. I feel like I never get to make decisions.', ...
        '4. I can find workable solutions to seemingly unsolvable problems.', ...
        '5. I seldom have choices when deciding how to behave.', ...
        '6. I am willing to work at creative solutions to problems.', ...
        '7. In any given situation, I am able to act appropriately.', ...
        '8. My behaviour is a result of conscious decisions that I make.', ...
        '9. I have many possible ways of behaving in any given situation.', ...
        '10. I have difficulty using my knowledge on a given topic in real life situations.', ...
        '11. I am willing to listen and consider alternatives for handling a problem.', ...
        '12. I have the self-confidence necessary to try different ways of behaving.'};
      
 save('items_string/items_CFS.mat', 'items_str')
 
 
% AQ10         
items_str = {'1. I often notice small sounds when others do not', ...
        '2. I usually concentrate more on the whole picture, rather than the small details', ...
        '3. I find it easy to do more than one thing at once', ...
        '4. If there is an interruption, I can switch back to what I was doing very quickly', ...
        '5. I find it easy to "read between the lines" when someone is talking to me', ...
        '6. I know how to tell if someone listenning to me is getting bored', ...
        '7. When I''m reading a story I find it difficult to work out the characters'' intentions', ...
        '8. I like to collect information about categories of things (e.g. types of car, types of bird, types of train, types of plant etc)', ...
        '9. I find it easy to work out what someone is thinking or feeling just by looking at their face', ...
        '10. I find it difficult to work out people''s intentions' };

 save('items_string/items_AQ10.mat', 'items_str')
 
 
% LSAS
items_str = {'1. Telephone in public.' , ...
                '2. Participating in small groups.' , ...
                '3. Eating in public places.' , ...
                '4. Drinking with others in public places.' , ...
                '5. Talking to people in authority.' , ...
                '6. Acting, performing or giving a talk in front of an audience.' , ...
                '7. Going to a party.' , ...
                '8. Working while being observed.' , ...
                '9. Writing while being observed .' , ...
                '10. Calling someone you don''t know very well .' , ...
                '11. Talking with people you don''t know very well .' , ...
                '12. Meeting strangers.' , ...
                '13. Urinating in a public bathroom.' , ...
                '14. Entering a room when others are already seated.' , ...
                '15. Being the centre of attention.' , ...
                '16. Speaking up at a meeting.' , ...
                '17. Taking a test .' , ...
                '18. Expressing a disagreement or disapproval to people you don''t know very well.' , ...
                '19. Looking at people you don''t very well in the eyes.' , ...
                '20. Giving a report to a group.' , ...
                '21. Trying to pick up someone.' , ...
                '22. Returning goods to a store .' , ...
                '23. Giving a party.' , ...
                '24. Resisting a high pressure salesperson'};
        
 save('items_string/items_LSAS.mat', 'items_str')     
